### ISSUE TITLE
[Suggestion] Netherending Ores

### ISSUE THREAD

**Issue by comp500** [phantamanta44/MekanismOres#11]
[Netherending Ores](https://www.curseforge.com/minecraft/mc-mods/netherending-ores) adds Nether and End ore equivalents for several mods. Could support be added for them to this mod?

**Comment by phantamanta44** [comment]
it's recommended that you simply pipe these ores through a smelter  first to convert them to overworld ores, which can then be processed as per usual (mirroring the behaviour of vanilla mekanism). however, i'll work on support anyways, possibly with a config option for toggling the behaviour.
