### ISSUE TITLE
terrafirmacraft ore support

### ISSUE THREAD

**Issue by drago87** [phantamanta44/MekanismOres#15]
I'm trying to make a private modpack and need what this mod adds but the Creativ tab is emty and JEI is emty.

The dropbox link contains a picture of the Creativ tab and JEI
All configs
Logs
Mods
and scritps
https://www.dropbox.com/sh/trwbgjbumlm1dh9/AADkr6jSsBfj0zeXk0XGLvGSa?dl=0

I have tried version 
1.12.2-2.0.10
1.12.2-2.0.11
1.12.2-2.0.12
Minecraft: 1.12.2
Forge: 14.23.5.2847
Mekanism: 1.12.2-9.8.3.390

I have another pack where it works

If i remove the mod i get a 
Missing minecraft:items:
mekores:mekanismore
error

**Comment by phantamanta44** [comment]
uh what do you expect to see? i don't actually recognize any mods in your pack that add new metal ores, and thus mekores doesn't have anything to do

**Comment by drago87** [comment]
TerraFirmaCraft and TFC-Metallum adds ores. However they are not standard ores so thats probebly why the Shards and whatnot dont show up.
 Is there a way to force them to show up?
 if not in a update is it possible to adda config to force specific processing chain stuff to show up?
Atleast from slurry to dust?

**Comment by phantamanta44** [comment]
support for each ore needs to be added manually in code. i've never played TFC before, which is why i missed it, i guess. will resolve soon

**Comment by phantamanta44** [comment]
after some research, i've decided that mekores will not support terrafirmacraft ore processing. i am of the opinion that terrafirmacraft is not designed to be played with traditional machinery mods and that there is no meaningful analogue to mekanism-style ore processing in the universe of tfc. i suggest adding processing recipes yourself using crafttweaker or similar if you really want to

**Comment by drago87** [comment]
I would like to do that but from what i understand your mod only adds the materials from slurry to dust if there is another mod that adds the "vanilla" style ores

**Comment by phantamanta44** [comment]
that is correct, and i do not plan on changing that. see [this reddit post](https://www.reddit.com/r/TerraFirmaCraft/comments/aqfu4m/comment/eggm8tp?utm_source=amp&utm_medium=&utm_content=comment_timestamp)
