### ISSUE TITLE
Memory usage issues from storing a copy of the texture atlas

### ISSUE THREAD

**Issue by itsmeow** [phantamanta44/MekanismOres#16]

**Comment by itsmeow** [comment]
Apparently GH just decided to create issue before I finished typing, but ClientEventListener is storing a whole copy of the texture atlas, which can get quite large. Is this 100% necessary? I'm not quite sure of a way you would get an ore color, but I am concerned with the memory overhead of storing an entire atlas copy in memory as that can get up there in size.

**Comment by phantamanta44** [comment]
this is a good point. i'll write a fix soon
