### ISSUE TITLE
[BUG?] Aluminum doesn't shown. 

### ISSUE THREAD

**Issue by DevTimur** [phantamanta44/MekanismOres#17]
Actually, not only Aluminum, but many other ores doesn't shown.
I don't understand what is wrong. Maybe i need to add ores to some list?

**Comment by phantamanta44** [comment]
ores are automatically detected and enabled, so if an ore isn't showing, then whatever mod you're using isn't registering it properly. can i get a mod list and a list of these "many other ores"?

**Comment by DevTimur** [comment]
Yeah, i was probably over-reacting. Not "many other ores", just Aluminum.
I'm not sure what cause only Aluminum to disapear. But here is a list of mods with aluminum I got:
1) Galacticraft Core
2) Galacticraft Planets
3) Thermal Foundation
4) Futurepack

I suspect it's something to do with Futurepack, because there is "Alutin crystal", wich is "kinda" aluminum ore, but not exactly.

Sorry, don't have time to test it atm. I'll close this issue, because probably that's my own fault.
