### ISSUE TITLE
[Suggestion] TAIGA Ores Integration

### ISSUE THREAD

**Issue by Freebi85** [phantamanta44/MekanismOres#3]
Hello =)
Thanks for the mod that saves me a lot of work :D
I'm definitely gonna put your mod in my pack. (If I have the permission)

I was wondering if you could also consider to add TAIGA's ores. (Tinkers Alloying Addon)
https://minecraft.curseforge.com/projects/taiga-tinkers-alloying-addon?gameCategorySlug=mc-mods&projectID=247661

My Modpack: https://minecraft.curseforge.com/projects/dungeons-dragons-and-space-shuttles?gameCategorySlug=modpacks&projectID=301717#c206
My Discord Channel: https://discordapp.com/invite/eUajYmK

Freebi

**Comment by phantamanta44** [comment]
note that taiga doesn't register oredict entries for `dilithium` for whatever reason, which means we can't support it

**Comment by Freebi85** [comment]
Thank you so much <3
I appreciate that.
