### ISSUE TITLE
[1.12.2 - 2.0.3] Crash: mekanism.api.gas.Gas cannot be cast to mekanism.api.gas.OreGas

### ISSUE THREAD

**Issue by CactusDuud** [phantamanta44/MekanismOres#5]
https://pastebin.com/UGGiBP2M

**Comment by phantamanta44** [comment]
this mod probably doesn't work with JAOPCA; why would you need both anyways?

**Comment by ApostolosRisen** [comment]
as it is I have possibly the exact same error, with out that mod included, but with the limited information I have I can't determine what's causing it 

https://pastebin.com/dbbsX5Jq <-- crash report
