### ISSUE TITLE
Gases are registered too late to be used with Crafttweaker

### ISSUE THREAD

**Issue by MightyBidoof** [phantamanta44/MekanismOres#7]
It's a minor issue, but the gases seem to be registered too late to be used with CrT.

Relevant Mods:
Mekanism Ver: 9.7.4.375
Mek Ores Ver: 2.0.4 (2.0.1 is displayed in brackets)
CrT Ver: 4.1.17

This error is spat out when the world opens:
![image](https://user-images.githubusercontent.com/12218253/57952720-ee28b580-78e5-11e9-93dc-dda8a7db785f.png)

/ct syntax thinks everything is fine, though:
![image](https://user-images.githubusercontent.com/12218253/57952777-19aba000-78e6-11e9-9c28-34b2d1840405.png)

Log incase it's needed:
[crafttweaker.log](https://github.com/phantamanta44/MekanismOres/files/3192910/crafttweaker.log)

Relevant Script:
``//Adds all slurries to the CDC``
``//The method is somewhat confusing since you'd expect to be able to set the input gas, but it's infact a static 100mb of sulfuric acid gas``
``//Imports``
``import crafttweaker.item.IItemStack;``
``import mod.mekanism.gas.IGasStack;``
``//Array - Ores - Order is as follows:``
``//Iron, Gold, Copper, Tin, Silver, Lead, Aluminium, Nickel, Starmetal, Platinum, Osmium, Lithium, Magnesium, Boron, Thorium, Uranium, Titanium, Iridium, Tungsten, Draconium (End)``
``val OArray = [<minecraft:iron_ore>, <minecraft:gold_ore>, <thermalfoundation:ore>, <thermalfoundation:ore:1>, <thermalfoundation:ore:2>, <thermalfoundation:ore:3>, <thermalfoundation:ore:4>, <thermalfoundation:ore:5>, <astralsorcery:blockcustomore:1>, <thermalfoundation:ore:6>, <mekanism:oreblock>, <nuclearcraft:ore:6>, <nuclearcraft:ore:7>, <nuclearcraft:ore:5>, <nuclearcraft:ore:3>, <nuclearcraft:ore:4>, <libvulpes:ore0:8>, <thermalfoundation:ore:7>, <techreborn:ore:8>, <draconicevolution:draconium_ore:2>] as IItemStack[];``
``//Array - Gas - Order is the same as the ores. Obviously.``
``val GArray = [<gas:iron>, <gas:gold>, <gas:copper>, <gas:tin>, <gas:silver>, <gas:lead>, <gas:aluminum>, <gas:nickel>, <gas:astral_starmetal>, <gas:platinum>, <gas:osmium>, <gas:lithium>, <gas:magnesium>, <gas:boron>, <gas:thorium>, <gas:uranium>, <gas:titanium>, <gas:iridium>, <gas:tungsten>, <gas:draconium>] as IGasStack[];``
``//Function``
``for i, item in OArray { 
mods.mekanism.chemical.dissolution.addRecipe(item, GArray[i] * 1000);
}``

**Comment by phantamanta44** [comment]
er out of curiosity, why do you need to do this using crafttweaker when the mod should already do this for you?

**Comment by MightyBidoof** [comment]
I'm doing a complete wipe of all oredict entries on items that don't need them.

And, because of this, i'm also trying to clean up any unnecessary recipes including the items I removed the entries from.
So, since i'm trying to clean it up, I have two options to do it:
The script above, paired with a removeAll.
Removing all the recipes I don't need.

Both of these don't work due to gases being registered too late, as  ``removeRecipe`` requires a gas to be specified.
And yea, I get that this is niche/not something your average user is going to do, so it won't surprise me if you don't consider this very important to fix.

**Comment by phantamanta44** [comment]
as it would happen, this is fixed in 21bb5435; i just kind of wanted to know the use case

**Comment by phantamanta44** [comment]
2.0.5 is available now: https://minecraft.curseforge.com/projects/mekanismores/files/2713093
