### ISSUE TITLE
Metal clean slurry

### ISSUE THREAD

**Issue by KokSaker** [phantamanta44/MekanismOres#9]
There is no *clean* slurry added by *MekanismOres*, instead mekanism Chemical Washer just duplicates it making iridium slurry to another iridium slurry.
Edit: iridium used as an example - this issue relevant to any ores that aren't supported by mekanism by default(without the *MekanismOres* mod).

**Comment by phantamanta44** [comment]
are you sure it's duplicating the slurry and you're not just confusing the dirty and clean slurry? both the clean and dirty slurry for metal X are just called "X Slurry"

**Comment by KokSaker** [comment]
Yeah, that's the case exactly. The naming is the issue. In Mekanism mod there are two kinds regular and *clean* slurry. Mekanism ores has both named similarly. This is just an inconvenience that would be good to get fixed.

**Comment by KokSaker** [comment]
Thank you!
